apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-leader
spec:
  schedule: "*/1 * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-leader
            image: acs23/update-leader:latest
          restartPolicy: OnFailure
